const clientWidth = document.body.clientWidth;
const moveX = clientWidth < 800 ? clientWidth - 200 : 1000;

const moveY = clientWidth < 800 ? 200 : 100;
const rate = clientWidth < 800 ? 0.8 : 0.5;
export const data = [
  {
    key: 0,
    name: '虾小哥',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 1,
    name: '铁碗饭',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 2,
    name: '陕老顺',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 3,
    name: '胖妈水饺',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 4,
    name: '聚光食堂',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 5,
    name: '迷上你',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 6,
    name: '望江面馆',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 7,
    name: '大鱼',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 8,
    name: '星耀城',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 9,
    name: '黄焖鸡',
    x: (Math.random() - rate) * moveX,
    y: (Math.random() - 0.5) * moveY,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 10,
    name: '炸酱面',
    x: (Math.random() - rate) * moveX,
    y: Math.random() * 50 - 25,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
  {
    key: 11,
    name: '海康新界(重新抽吧)',
    x: (Math.random() - rate) * moveX,
    y: Math.random() * 50 - 25,
    z: Math.round(Math.random() * 90),
    deg: Math.random() * 180,
  },
];
